"""empty message

Revision ID: 39a61fa5ec11
Revises: a66ad4eed5ec
Create Date: 2023-01-20 14:34:08.650087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a61fa5ec11'
down_revision = 'a66ad4eed5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
