"""empty message

Revision ID: 77d424c3cb44
Revises: 9b1c0b834b0f
Create Date: 2023-01-22 21:23:39.175285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d424c3cb44'
down_revision = '9b1c0b834b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
