"""empty message

Revision ID: 802b72ae77ea
Revises: 39a61fa5ec11
Create Date: 2023-01-20 14:39:24.405651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802b72ae77ea'
down_revision = '39a61fa5ec11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
