"""empty message

Revision ID: 9b1c0b834b0f
Revises: bd83576fb7d5
Create Date: 2023-01-21 20:26:32.477545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1c0b834b0f'
down_revision = 'bd83576fb7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
